version: "3.0"
services:
  app:
    build: "."
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - NPM_TOKEN=${NPM_TOKEN:-}
    volumes:
      - ./:/home/node/application/app:delegated
      - /home/node/application/app/node_modules/
