pr: none

trigger:
  batch: true
  branches:
    include:
    - master

stages:

- stage: Build
  pool:
    vmImage: ubuntu-16.04
  variables:
  - group: node-cli--build
  jobs:
  - job: Build
    displayName: Test and publish
    steps:

    - script: |
        docker build \
          --tag build-runner \
          .
      displayName: Prepare CI Docker image

    - script: |
        docker run \
          --rm \
          --user "$(id -u):$(id -g)" \
          --volume "$(pwd):/home/node/app" \
          build-runner \
          npm install
      displayName: Install dependencies

    - script: |
        docker run \
          --rm \
          --user "$(id -u):$(id -g)" \
          --volume "$(pwd):/home/node/app" \
          build-runner \
          npm test
      displayName: Run tests

    - script: |
        docker run \
          -e "CI=true" \
          -e "GITHUB_TOKEN=$(GITHUB_TOKEN)" \
          -e "NPM_TOKEN=$(NPM_TOKEN)" \
          --rm \
          --user "$(id -u):$(id -g)" \
          --volume "$(pwd):/home/node/app" \
          build-runner \
          npx semantic-release
      displayName: Release
