pr:
  branches:
    include:
    - '*'

trigger: none

stages:
- stage: CI
  variables:
  - group: node-cli--ci
  pool:
    vmImage: ubuntu-16.04
  jobs:
  - job: CI
    displayName: Prepare and run tests
    steps:
    - script: |
        docker build \
          --tag ci-runner \
          .
      displayName: Prepare CI Docker image
    - script: |
        docker run \
          --rm \
          --user "$(id -u):$(id -g)" \
          --volume "$(pwd):/home/node/app" \
          ci-runner \
          npm install
      displayName: Install dependencies
    - script: |
        docker run \
          --rm \
          --user "$(id -u):$(id -g)" \
          --volume "$(pwd):/home/node/app" \
          ci-runner \
          npm test
      displayName: Run tests
